on: {"push":{"branches":["main"]}}
jobs:
  build:
    # environment: "iosevka-lyte.cachix.org"
    name: build and cache
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: iosevka-lyte
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --accept-flake-config
